// client/src/components/dashboard/SectionEditor.vue
<script setup lang="ts">
import { computed } from "vue";
import { type InvitationSection } from "@/lib/types";
import { useInvitationStore } from "@/stores/invitation";
import Input from "@/components/ui/Input.vue";
import Textarea from "@/components/ui/Textarea.vue";
import Label from "@/components/ui/Label.vue";
import Button from "@/components/ui/Button.vue";
import { Upload } from "lucide-vue-next";

interface Props {
  section: InvitationSection;
}

const props = defineProps<Props>();
const store = useInvitationStore();

const handleTextChange = (key: string, value: string) => {
  store.updateSection(props.section.id, {
    data: {
      ...props.section.data,
      [key]: value,
    },
  });
};

const renderTextFields = computed(() => {
  return Object.entries(props.section.data)
    .filter(([key, value]) => {
      // Filter logic similar to legacy: string, not ID/Type/Image
      return (
        typeof value === "string" &&
        key !== "id" &&
        key !== "type" &&
        key !== "image"
      );
    })
    .map(([key, value]) => ({
        key,
        value: value as string,
        label: key.replace(/([A-Z])/g, " $1").trim(),
        isLongText: (value as string).length > 50 || key === "message" || key === "quote"
    }));
});
</script>

<template>
  <div class="pb-12">
    <h3 class="text-lg font-semibold mb-4 flex items-center gap-2 capitalize">
      Edit {{ section.title }}
    </h3>

    <!-- Maps specific editor -->
    <div v-if="section.type === 'maps'" class="space-y-6">
      <div class="space-y-2">
        <Label>Location Image</Label>
        <div
          class="border-2 border-dashed border-gray-200 rounded-lg p-6 flex flex-col items-center justify-center bg-gray-50 hover:bg-gray-100 transition-colors cursor-pointer"
        >
          <div v-if="(section.data as any).image" class="relative w-full aspect-video mb-4">
            <img
              :src="(section.data as any).image as string"
              alt="Location"
              class="object-cover rounded-md w-full h-full"
            />
            <Button
              variant="destructive"
              size="sm"
              class="absolute top-2 right-2"
              @click="handleTextChange('image', '')"
            >
              Remove
            </Button>
          </div>
          <div v-else class="text-center">
            <div
              class="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-3"
            >
              <Upload class="w-6 h-6" />
            </div>
            <p class="text-sm font-medium text-gray-900">Click to upload image</p>
            <p class="text-xs text-gray-500 mt-1">SVG, PNG, JPG or GIF (max. 2MB)</p>
            <div class="mt-4 flex gap-2">
              <Input
                placeholder="Or paste image URL..."
                :model-value="((section.data as any).image as string) || ''"
                @update:model-value="(val) => handleTextChange('image', val)"
              />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Generic Fields -->
    <div v-for="field in renderTextFields" :key="field.key" class="space-y-2 mb-4">
      <Label :for="field.key" class="capitalize">{{ field.label }}</Label>
      <Textarea
        v-if="field.isLongText"
        :id="field.key"
        :model-value="field.value"
        @update:model-value="(val) => handleTextChange(field.key, val)"
        class="min-h-[100px]"
      />
      <Input
        v-else
        :id="field.key"
        :model-value="field.value"
        @update:model-value="(val) => handleTextChange(field.key, val)"
      />
    </div>

    <div class="flex justify-end mt-4">
      <Button variant="outline" size="sm"> Reset to Default </Button>
    </div>
  </div>
</template>

// components/dashboard/SectionEditor.tsx
import React from 'react';
import { InvitationSection } from '@/lib/types';
import { useInvitationStore } from '@/lib/store';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { Textarea } from '@/components/ui/Textarea';
import { Button } from '@/components/ui/Button';
import { Image as ImageIcon, Upload } from 'lucide-react';

interface SectionEditorProps {
    section: InvitationSection;
}

export function SectionEditor({ section }: SectionEditorProps) {
    const updateSection = useInvitationStore((state) => state.updateSection);

    const handleTextChange = (key: string, value: string) => {
        updateSection(section.id, {
            data: {
                ...section.data,
                [key]: value,
            },
        });
    };

    // Helper to render text inputs for generic data fields
    const renderTextFields = () => {
        // Filter out non-text fields or complex objects for this simple editor
        // In a real app, you'd have specific forms for each section type
        // For this task, "user hanya bisa mengedit kalimatnya" (user can only edit sentences)
        // So we'll try to find string properties in the data object.

        return Object.entries(section.data).map(([key, value]) => {
            if (typeof value === 'string' && key !== 'id' && key !== 'type' && key !== 'image') {
                // Use Textarea for longer text, Input for shorter
                const isLongText = value.length > 50 || key === 'message' || key === 'quote';

                return (
                    <div key={key} className="space-y-2 mb-4">
                        <Label htmlFor={key} className="capitalize">
                            {key.replace(/([A-Z])/g, ' $1').trim()}
                        </Label>
                        {isLongText ? (
                            <Textarea
                                id={key}
                                value={value}
                                onChange={(e) => handleTextChange(key, e.target.value)}
                                className="min-h-[100px]"
                            />
                        ) : (
                            <Input
                                id={key}
                                value={value}
                                onChange={(e) => handleTextChange(key, e.target.value)}
                            />
                        )}
                    </div>
                );
            }
            return null;
        });
    };

    const renderMapsEditor = () => {
        // Maps specific editor: Image Upload + Text
        const mapsData = section.data as any; // Cast to any for easier access to specific fields

        return (
            <div className="space-y-6">
                {/* Image Upload Area */}
                <div className="space-y-2">
                    <Label>Location Image</Label>
                    <div className="border-2 border-dashed border-gray-200 rounded-lg p-6 flex flex-col items-center justify-center bg-gray-50 hover:bg-gray-100 transition-colors cursor-pointer">
                        {mapsData.image ? (
                            <div className="relative w-full aspect-video mb-4">
                                <img
                                    src={mapsData.image}
                                    alt="Location"
                                    className="w-full h-full object-cover rounded-md"
                                />
                                <Button
                                    variant="destructive"
                                    size="sm"
                                    className="absolute top-2 right-2"
                                    onClick={() => handleTextChange('image', '')}
                                >
                                    Remove
                                </Button>
                            </div>
                        ) : (
                            <div className="text-center">
                                <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-3">
                                    <Upload size={24} />
                                </div>
                                <p className="text-sm font-medium text-gray-900">Click to upload image</p>
                                <p className="text-xs text-gray-500 mt-1">SVG, PNG, JPG or GIF (max. 2MB)</p>
                                {/* Mock Input for URL since we don't have backend */}
                                <div className="mt-4 flex gap-2">
                                    <Input
                                        placeholder="Or paste image URL..."
                                        onChange={(e) => handleTextChange('image', e.target.value)}
                                    />
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Standard Text Fields for Maps */}
                {renderTextFields()}
            </div>
        );
    };

    return (
        <div className="p-4 bg-white border rounded-lg shadow-sm mt-2">
            <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                Edit {section.title}
            </h3>

            {section.type === 'maps' ? renderMapsEditor() : renderTextFields()}

            <div className="flex justify-end mt-4">
                <Button variant="outline" size="sm">
                    Reset to Default
                </Button>
            </div>
        </div>
    );
}
