// _legacy/components/dashboard/AddSectionButton.tsx
'use client';

import React from 'react';
import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/Button';

export const AddSectionButton: React.FC = () => {
    return (
        <Button
            variant="outline"
            className="w-full border-2 border-dashed border-teal-300 text-teal-600 hover:bg-teal-50 hover:border-teal-400"
        >
            <Plus className="w-5 h-5 mr-2" />
            Tambah Halaman
        </Button>
    );
};

// client/src/components/dashboard/AddSectionButton.vue
<script setup lang="ts">
import Button from "@/components/ui/Button.vue";
import { Plus } from "lucide-vue-next";
</script>

<template>
  <Button
    variant="dashed"
    class="w-full h-12 border-2 border-dashed border-gray-300 text-gray-500 hover:border-blue-500 hover:text-blue-500 hover:bg-blue-50"
  >
    <Plus class="w-5 h-5 mr-2" />
    Tambah Bagian Baru
  </Button>
</template>
