// components/dashboard/DashboardHeader.tsx
'use client';

import React, { useState } from 'react';
import { ArrowLeft, Palette, Settings } from 'lucide-react';
import { useInvitationStore } from '@/lib/store';
import { useTemplateStore } from '@/lib/template-store';
import { Button } from '@/components/ui/Button';
import { TemplateSelector } from './TemplateSelector';

export const DashboardHeader: React.FC = () => {
    const invitation = useInvitationStore((state) => state.invitation);
    const templates = useTemplateStore((state) => state.templates);
    const [showTemplateSelector, setShowTemplateSelector] = useState(false);

    const currentTemplate = templates.find((t) => t.id === invitation.templateId);

    return (
        <>
            <div className="bg-white border-b border-gray-200 px-6 py-4">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                            <ArrowLeft className="w-5 h-5 text-gray-700" />
                        </button>
                        <div>
                            <h1 className="text-xl font-semibold text-gray-900">{invitation.title}</h1>
                            <p className="text-sm text-gray-500">
                                {currentTemplate ? `Template: ${currentTemplate.name}` : 'No template selected'}
                            </p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={() => setShowTemplateSelector(true)}
                            className="flex items-center gap-2"
                        >
                            <Palette size={16} />
                            Change Template
                        </Button>
                        <Button variant="ghost" size="sm">
                            <Settings size={16} />
                        </Button>
                    </div>
                </div>
            </div>
            <TemplateSelector
                isOpen={showTemplateSelector}
                onClose={() => setShowTemplateSelector(false)}
            />
        </>
    );
};

// client/src/components/dashboard/DashboardHeader.vue
<script setup lang="ts">
import Button from "@/components/ui/Button.vue";
import { Settings } from "lucide-vue-next";
</script>

<template>
  <header
    class="sticky top-0 z-30 flex items-center justify-between px-6 py-4 bg-white/80 backdrop-blur-md border-b border-gray-100"
  >
    <div class="flex items-center gap-2">
      <div class="w-8 h-8 bg-gradient-to-br from-blue-600 to-teal-400 rounded-lg flex items-center justify-center text-white font-bold text-lg">
        T
      </div>
      <h1 class="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-teal-500">
        Tamu.id
      </h1>
    </div>

    <div class="flex items-center gap-3">
      <Button variant="ghost" size="icon" class="text-gray-500 hover:text-gray-700">
        <Settings class="w-5 h-5" />
      </Button>
      <div class="h-6 w-px bg-gray-200"></div>
      <div class="flex items-center gap-3">
        <div class="text-right hidden sm:block">
          <p class="text-sm font-medium text-gray-900">Admin User</p>
          <p class="text-xs text-gray-500">admin@tamu.id</p>
        </div>
        <div class="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center overflow-hidden border border-gray-200">
           <!-- Placeholder Avatar -->
           <span class="text-xs font-semibold text-gray-600">AU</span>
        </div>
      </div>
    </div>
  </header>
</template>
