// components/ui/Label.tsx
import * as React from "react"
import { cn } from "@/lib/utils/cn"

export interface LabelProps
    extends React.LabelHTMLAttributes<HTMLLabelElement> { }

const Label = React.forwardRef<HTMLLabelElement, LabelProps>(
    ({ className, ...props }, ref) => (
        <label
            ref={ref}
            className={cn(
                "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
                className
            )}
            {...props}
        />
    )
)
Label.displayName = "Label"

export { Label }

// client/src/components/ui/Label.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";

interface Props {
  class?: string;
  for?: string;
}

defineProps<Props>();
</script>

<template>
  <label
    :for="for"
    :class="
      cn(
        'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
        $props.class
      )
    "
  >
    <slot />
  </label>
</template>
